### ISSUE TITLE
Support linking straight to sections of Markdown content

### ISSUE THREAD

**Issue by thibaudcolas** [djangocon/2021.djangocon.eu#10]
I think it would help a lot with the code of conduct team’s work if we could link straight to specific parts of the code of conduct – for example, on https://2021.djangocon.eu/conduct/code_of_conduct/, I would like to be able to link to the "Where to report incidents" sub-section with a hash like: https://2021.djangocon.eu/conduct/code_of_conduct/#where-to-report-incidents.

The site seems to be using the `markdown` package, so making this happen could be as simple as enabling the [toc](https://python-markdown.github.io/extensions/toc/) extension. I think enabling the extension should be enough so headings have an `id` based on their slugified text, but it might also be worth looking into [other options](https://python-markdown.github.io/extensions/toc/#usage) we could make use of.

**Comment by magamig** [comment]
Hi @thibaudcolas, that is already implemented in the website. It is not working in the CoC page because it is all in the same file. For it to work just split the `.md` file in smaller files corresponding to each section. 
Here is an example: [https://2021.djangocon.eu/about/contact/#assets](https://2021.djangocon.eu/about/contact/#assets)

**Comment by thibaudcolas** [comment]
@magamig I went with what I proposed in #16 🙈 I hope that’s ok, let me know what you think.

**Comment by magamig** [comment]
It's live and working :)
https://2021.djangocon.eu/conduct/code_of_conduct/#guidelines-for-reporting-incidents
